base_fare = 110  # base fare
tim_fare_permin = 0.4  # time fare per min
Drop_dist = 1  # drop distance
Drop_tim = 7  # drop time
max_drp_time = 9  # MAXIMUM DROP TIME
max_drp_time_permin = 20  # maximum drop time per min
ref_perc = 0  # referral percentage
DF1_per = 1  # distance fare bw 0 and 2 kms
DF2_per = 5  # distance fare bw 2 and 4 kms
DF3_per = 30  # distance fare bw 4 and 6 kms
DF4_per = 15  # distance fare bw 6 and 10 kms
DF5_per = 18  # distance fare bw 10 and 200 kms
Tax_GST_perc = 5  # GST percentage
peak_tperc = 25  # peak time percentage charges
peak_time = False  # peak time
lpf_per = 1  # late pickup fare per minute
delay_time = 0  # in seconds
pickup_dist = 1  # pickup distance
pck_crg_permin = 10  # pickup charges per
pck_limit_cap = 3

cancel = False
# minimum distance driver should travel for cancellation fee to apply in kms
min_dist_cncl = 1.8
min_time_cncl = 3  # minimum time duration in which cancellation fee is applied in mins
cncl_fee_perkm = 15
cncl_fee_permin = 20
cncl_dist = 3
cncl_time = 5
